DOMAIN = "bluelab_guardian"
CONF_API_TOKEN = "api_token"
CONF_ORGANIZATION_ID = "organization_id"
TELEMETRY_URL = "https://api.edenic.io/api/v1/telemetry/"
DEVICE_LIST_URL = "https://api.edenic.io/api/v1/device/"
DEVICE_ATTRIBUTE_URL = "https://api.edenic.io/api/v1/device-attribute/"
